# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/motorola/dubai/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),dubai)

$(call add-radio-file-sha1-checked,radio/bluetooth.img,ce72be54dc4754fb6a0e8e4ef799477be230fbcc)
$(call add-radio-file-sha1-checked,radio/modem.img,153b510f9df5af5b00cc52bf7b414239d873d6bc)
$(call add-radio-file-sha1-checked,radio/abl.img,80df7ab3905868653e4bd8a9c87d29e2c16415c4)
$(call add-radio-file-sha1-checked,radio/aop.img,0c0ee97e3589c519d7ce33a094f0588601b88667)
$(call add-radio-file-sha1-checked,radio/cpucp.img,4b3a135e0b10778c415ebddba6d188742a8d7356)
$(call add-radio-file-sha1-checked,radio/devcfg.img,3fc260db61c462e699807c0035afd8ccbb0cfe8c)
$(call add-radio-file-sha1-checked,radio/dsp.img,72c78cc1886db44fdb7893f8734a002552151a50)
$(call add-radio-file-sha1-checked,radio/fsg.img,0c57bd6d4e001b0cf48e74e14babb837de158dd2)
$(call add-radio-file-sha1-checked,radio/hyp.img,75ab7c29117b3d5376e52ff41dd287e37c6581bc)
$(call add-radio-file-sha1-checked,radio/keymaster.img,f879258026bd5f27ca4e3cc9b3cb7cb196339e38)
$(call add-radio-file-sha1-checked,radio/logo.img,b577850f84826f3ea46a9140c94297c827c2248b)
$(call add-radio-file-sha1-checked,radio/prov.img,3e05c6d636212b73bdc58350059d3517fa23235b)
$(call add-radio-file-sha1-checked,radio/qupfw.img,f35743dbb706fa098dd944faefae325676e93f01)
$(call add-radio-file-sha1-checked,radio/shrm.img,4ff43fa936b9ac06e818aa94a4768644d82bccc5)
$(call add-radio-file-sha1-checked,radio/storsec.img,48bce3bcb14f9892653c30320f3f94463b097297)
$(call add-radio-file-sha1-checked,radio/tz.img,980ef5eb3bd6d44cc59041f8b3d3bba1173f8e20)
$(call add-radio-file-sha1-checked,radio/uefisecapp.img,9b8ad09e8d84663467c5a05f4b7b6bd550cc5477)
$(call add-radio-file-sha1-checked,radio/xbl.img,d1e6690ec28b37ee6de96ac42ee71a3ee2c4cb85)
$(call add-radio-file-sha1-checked,radio/xbl_config.img,1648c132aaabad44a6a054deee70fe1bd6b0309c)

endif
